// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ConfigProto.proto</summary>
public static partial class ConfigProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for ConfigProto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ConfigProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFDb25maWdQcm90by5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFt",
          "cC5wcm90bxoMUmV3YXJkLnByb3RvIpYCCgZjb25maWcSNAoQbGFzdFVwZGF0",
          "ZUF2YXRhchgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMwoP",
          "bGFzdFVwZGF0ZUZyYW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVz",
          "dGFtcBI4ChRsYXN0VXBkYXRlQmFja2dyb3VuZBgDIAEoCzIaLmdvb2dsZS5w",
          "cm90b2J1Zi5UaW1lc3RhbXASEwoLcmVzZXRBdmF0YXIYBCABKAUSEgoKcmVz",
          "ZXRGcmFtZRgFIAEoBRIXCg9yZXNldEJhY2tncm91bmQYBiABKAUSJQoNcmV3",
          "YXJkSW52aXRlZBgHIAMoCzIOLlJld2FyZEludml0ZWQiOAoNUmV3YXJkSW52",
          "aXRlZBIOCgZudW1iZXIYASABKAUSFwoGcmV3YXJkGAIgASgLMgcuUmV3YXJk",
          "IjwKEWxpc3RSZXdhcmRJbnZpdGVkEg4KBm51bWJlchgBIAEoBRIXCgZyZXdh",
          "cmQYAiABKAsyBy5SZXdhcmRiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::RewardReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::config), global::config.Parser, new[]{ "LastUpdateAvatar", "LastUpdateFrame", "LastUpdateBackground", "ResetAvatar", "ResetFrame", "ResetBackground", "RewardInvited" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RewardInvited), global::RewardInvited.Parser, new[]{ "Number", "Reward" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::listRewardInvited), global::listRewardInvited.Parser, new[]{ "Number", "Reward" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class config : pb::IMessage<config>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<config> _parser = new pb::MessageParser<config>(() => new config());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<config> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ConfigProtoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public config() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public config(config other) : this() {
    lastUpdateAvatar_ = other.lastUpdateAvatar_ != null ? other.lastUpdateAvatar_.Clone() : null;
    lastUpdateFrame_ = other.lastUpdateFrame_ != null ? other.lastUpdateFrame_.Clone() : null;
    lastUpdateBackground_ = other.lastUpdateBackground_ != null ? other.lastUpdateBackground_.Clone() : null;
    resetAvatar_ = other.resetAvatar_;
    resetFrame_ = other.resetFrame_;
    resetBackground_ = other.resetBackground_;
    rewardInvited_ = other.rewardInvited_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public config Clone() {
    return new config(this);
  }

  /// <summary>Field number for the "lastUpdateAvatar" field.</summary>
  public const int LastUpdateAvatarFieldNumber = 1;
  private global::Google.Protobuf.WellKnownTypes.Timestamp lastUpdateAvatar_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp LastUpdateAvatar {
    get { return lastUpdateAvatar_; }
    set {
      lastUpdateAvatar_ = value;
    }
  }

  /// <summary>Field number for the "lastUpdateFrame" field.</summary>
  public const int LastUpdateFrameFieldNumber = 2;
  private global::Google.Protobuf.WellKnownTypes.Timestamp lastUpdateFrame_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp LastUpdateFrame {
    get { return lastUpdateFrame_; }
    set {
      lastUpdateFrame_ = value;
    }
  }

  /// <summary>Field number for the "lastUpdateBackground" field.</summary>
  public const int LastUpdateBackgroundFieldNumber = 3;
  private global::Google.Protobuf.WellKnownTypes.Timestamp lastUpdateBackground_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp LastUpdateBackground {
    get { return lastUpdateBackground_; }
    set {
      lastUpdateBackground_ = value;
    }
  }

  /// <summary>Field number for the "resetAvatar" field.</summary>
  public const int ResetAvatarFieldNumber = 4;
  private int resetAvatar_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ResetAvatar {
    get { return resetAvatar_; }
    set {
      resetAvatar_ = value;
    }
  }

  /// <summary>Field number for the "resetFrame" field.</summary>
  public const int ResetFrameFieldNumber = 5;
  private int resetFrame_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ResetFrame {
    get { return resetFrame_; }
    set {
      resetFrame_ = value;
    }
  }

  /// <summary>Field number for the "resetBackground" field.</summary>
  public const int ResetBackgroundFieldNumber = 6;
  private int resetBackground_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ResetBackground {
    get { return resetBackground_; }
    set {
      resetBackground_ = value;
    }
  }

  /// <summary>Field number for the "rewardInvited" field.</summary>
  public const int RewardInvitedFieldNumber = 7;
  private static readonly pb::FieldCodec<global::RewardInvited> _repeated_rewardInvited_codec
      = pb::FieldCodec.ForMessage(58, global::RewardInvited.Parser);
  private readonly pbc::RepeatedField<global::RewardInvited> rewardInvited_ = new pbc::RepeatedField<global::RewardInvited>();
  /// <summary>
  /// các mức nhận phần thưởng khi mời
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::RewardInvited> RewardInvited {
    get { return rewardInvited_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as config);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(config other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(LastUpdateAvatar, other.LastUpdateAvatar)) return false;
    if (!object.Equals(LastUpdateFrame, other.LastUpdateFrame)) return false;
    if (!object.Equals(LastUpdateBackground, other.LastUpdateBackground)) return false;
    if (ResetAvatar != other.ResetAvatar) return false;
    if (ResetFrame != other.ResetFrame) return false;
    if (ResetBackground != other.ResetBackground) return false;
    if(!rewardInvited_.Equals(other.rewardInvited_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (lastUpdateAvatar_ != null) hash ^= LastUpdateAvatar.GetHashCode();
    if (lastUpdateFrame_ != null) hash ^= LastUpdateFrame.GetHashCode();
    if (lastUpdateBackground_ != null) hash ^= LastUpdateBackground.GetHashCode();
    if (ResetAvatar != 0) hash ^= ResetAvatar.GetHashCode();
    if (ResetFrame != 0) hash ^= ResetFrame.GetHashCode();
    if (ResetBackground != 0) hash ^= ResetBackground.GetHashCode();
    hash ^= rewardInvited_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (lastUpdateAvatar_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(LastUpdateAvatar);
    }
    if (lastUpdateFrame_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(LastUpdateFrame);
    }
    if (lastUpdateBackground_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(LastUpdateBackground);
    }
    if (ResetAvatar != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(ResetAvatar);
    }
    if (ResetFrame != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(ResetFrame);
    }
    if (ResetBackground != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(ResetBackground);
    }
    rewardInvited_.WriteTo(output, _repeated_rewardInvited_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (lastUpdateAvatar_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(LastUpdateAvatar);
    }
    if (lastUpdateFrame_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(LastUpdateFrame);
    }
    if (lastUpdateBackground_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(LastUpdateBackground);
    }
    if (ResetAvatar != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(ResetAvatar);
    }
    if (ResetFrame != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(ResetFrame);
    }
    if (ResetBackground != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(ResetBackground);
    }
    rewardInvited_.WriteTo(ref output, _repeated_rewardInvited_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (lastUpdateAvatar_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdateAvatar);
    }
    if (lastUpdateFrame_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdateFrame);
    }
    if (lastUpdateBackground_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdateBackground);
    }
    if (ResetAvatar != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResetAvatar);
    }
    if (ResetFrame != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResetFrame);
    }
    if (ResetBackground != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResetBackground);
    }
    size += rewardInvited_.CalculateSize(_repeated_rewardInvited_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(config other) {
    if (other == null) {
      return;
    }
    if (other.lastUpdateAvatar_ != null) {
      if (lastUpdateAvatar_ == null) {
        LastUpdateAvatar = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      LastUpdateAvatar.MergeFrom(other.LastUpdateAvatar);
    }
    if (other.lastUpdateFrame_ != null) {
      if (lastUpdateFrame_ == null) {
        LastUpdateFrame = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      LastUpdateFrame.MergeFrom(other.LastUpdateFrame);
    }
    if (other.lastUpdateBackground_ != null) {
      if (lastUpdateBackground_ == null) {
        LastUpdateBackground = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      LastUpdateBackground.MergeFrom(other.LastUpdateBackground);
    }
    if (other.ResetAvatar != 0) {
      ResetAvatar = other.ResetAvatar;
    }
    if (other.ResetFrame != 0) {
      ResetFrame = other.ResetFrame;
    }
    if (other.ResetBackground != 0) {
      ResetBackground = other.ResetBackground;
    }
    rewardInvited_.Add(other.rewardInvited_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (lastUpdateAvatar_ == null) {
            LastUpdateAvatar = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(LastUpdateAvatar);
          break;
        }
        case 18: {
          if (lastUpdateFrame_ == null) {
            LastUpdateFrame = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(LastUpdateFrame);
          break;
        }
        case 26: {
          if (lastUpdateBackground_ == null) {
            LastUpdateBackground = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(LastUpdateBackground);
          break;
        }
        case 32: {
          ResetAvatar = input.ReadInt32();
          break;
        }
        case 40: {
          ResetFrame = input.ReadInt32();
          break;
        }
        case 48: {
          ResetBackground = input.ReadInt32();
          break;
        }
        case 58: {
          rewardInvited_.AddEntriesFrom(input, _repeated_rewardInvited_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (lastUpdateAvatar_ == null) {
            LastUpdateAvatar = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(LastUpdateAvatar);
          break;
        }
        case 18: {
          if (lastUpdateFrame_ == null) {
            LastUpdateFrame = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(LastUpdateFrame);
          break;
        }
        case 26: {
          if (lastUpdateBackground_ == null) {
            LastUpdateBackground = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(LastUpdateBackground);
          break;
        }
        case 32: {
          ResetAvatar = input.ReadInt32();
          break;
        }
        case 40: {
          ResetFrame = input.ReadInt32();
          break;
        }
        case 48: {
          ResetBackground = input.ReadInt32();
          break;
        }
        case 58: {
          rewardInvited_.AddEntriesFrom(ref input, _repeated_rewardInvited_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class RewardInvited : pb::IMessage<RewardInvited>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RewardInvited> _parser = new pb::MessageParser<RewardInvited>(() => new RewardInvited());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RewardInvited> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ConfigProtoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RewardInvited() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RewardInvited(RewardInvited other) : this() {
    number_ = other.number_;
    reward_ = other.reward_ != null ? other.reward_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RewardInvited Clone() {
    return new RewardInvited(this);
  }

  /// <summary>Field number for the "number" field.</summary>
  public const int NumberFieldNumber = 1;
  private int number_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Number {
    get { return number_; }
    set {
      number_ = value;
    }
  }

  /// <summary>Field number for the "reward" field.</summary>
  public const int RewardFieldNumber = 2;
  private global::Reward reward_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Reward Reward {
    get { return reward_; }
    set {
      reward_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RewardInvited);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RewardInvited other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Number != other.Number) return false;
    if (!object.Equals(Reward, other.Reward)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Number != 0) hash ^= Number.GetHashCode();
    if (reward_ != null) hash ^= Reward.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Number != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Number);
    }
    if (reward_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Reward);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Number != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Number);
    }
    if (reward_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Reward);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Number != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Number);
    }
    if (reward_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reward);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RewardInvited other) {
    if (other == null) {
      return;
    }
    if (other.Number != 0) {
      Number = other.Number;
    }
    if (other.reward_ != null) {
      if (reward_ == null) {
        Reward = new global::Reward();
      }
      Reward.MergeFrom(other.Reward);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Number = input.ReadInt32();
          break;
        }
        case 18: {
          if (reward_ == null) {
            Reward = new global::Reward();
          }
          input.ReadMessage(Reward);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Number = input.ReadInt32();
          break;
        }
        case 18: {
          if (reward_ == null) {
            Reward = new global::Reward();
          }
          input.ReadMessage(Reward);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class listRewardInvited : pb::IMessage<listRewardInvited>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<listRewardInvited> _parser = new pb::MessageParser<listRewardInvited>(() => new listRewardInvited());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<listRewardInvited> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ConfigProtoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public listRewardInvited() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public listRewardInvited(listRewardInvited other) : this() {
    number_ = other.number_;
    reward_ = other.reward_ != null ? other.reward_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public listRewardInvited Clone() {
    return new listRewardInvited(this);
  }

  /// <summary>Field number for the "number" field.</summary>
  public const int NumberFieldNumber = 1;
  private int number_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Number {
    get { return number_; }
    set {
      number_ = value;
    }
  }

  /// <summary>Field number for the "reward" field.</summary>
  public const int RewardFieldNumber = 2;
  private global::Reward reward_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Reward Reward {
    get { return reward_; }
    set {
      reward_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as listRewardInvited);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(listRewardInvited other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Number != other.Number) return false;
    if (!object.Equals(Reward, other.Reward)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Number != 0) hash ^= Number.GetHashCode();
    if (reward_ != null) hash ^= Reward.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Number != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Number);
    }
    if (reward_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Reward);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Number != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Number);
    }
    if (reward_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Reward);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Number != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Number);
    }
    if (reward_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reward);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(listRewardInvited other) {
    if (other == null) {
      return;
    }
    if (other.Number != 0) {
      Number = other.Number;
    }
    if (other.reward_ != null) {
      if (reward_ == null) {
        Reward = new global::Reward();
      }
      Reward.MergeFrom(other.Reward);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Number = input.ReadInt32();
          break;
        }
        case 18: {
          if (reward_ == null) {
            Reward = new global::Reward();
          }
          input.ReadMessage(Reward);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Number = input.ReadInt32();
          break;
        }
        case 18: {
          if (reward_ == null) {
            Reward = new global::Reward();
          }
          input.ReadMessage(Reward);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
