//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/HCGameUnity/Input/HCInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @HCInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @HCInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""HCInputAction"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""c8f6a3af-ea28-4005-b3ca-b247d8a4d780"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Value"",
                    ""id"": ""e6112cae-fe5f-4317-b086-d74531e63e9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftHold"",
                    ""type"": ""Button"",
                    ""id"": ""0a47281b-8276-436a-852a-7e2f357c1543"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RClick"",
                    ""type"": ""Button"",
                    ""id"": ""3ffdcd76-9966-4090-b850-7b35d919b2fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""5c729eb7-f941-44d0-b2b0-644332bfa09d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""abdf94cd-2997-4e60-b66f-aaee13810d8b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""5bee3757-b4a9-4e8a-98d4-f97799362fa2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""ea9914a5-ef7f-4cd7-8001-f24dbe3922c1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""fc01c924-6e94-4142-9325-f620c505ec76"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryFingerDelta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""718e329a-6836-45e3-b262-e7b4b90348d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchHold"",
                    ""type"": ""Button"",
                    ""id"": ""51fe3add-1670-4beb-9276-a32c5ea00d71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.15)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPress"",
                    ""type"": ""PassThrough"",
                    ""id"": ""683ff5f8-48b3-41a1-a69c-c8938d266bae"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchContact"",
                    ""type"": ""Button"",
                    ""id"": ""3eba763a-31ac-4bca-b9d2-fbb2d2d4a246"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46a05df9-77cf-43b7-9e97-474c04cdcd07"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6263372-6ff9-4625-b848-96e6f32540d3"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ca83f8a-489b-4886-9e10-f825b7c959e2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c51d791-522d-43e6-9df7-c0986d124aab"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70bdf61b-98ef-40b6-99f1-3b1ea8c886cb"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""187629dc-a3ba-4f19-85fc-2eaaf47e2948"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0434fd7-da86-4ffd-9f75-090b9d32da32"",
                    ""path"": ""<Touchscreen>/touch0/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryFingerDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fd5144d-bf82-4597-9265-cd3d16889c8e"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""428f1e4c-573d-4944-95ee-0d43d83db156"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbba956c-32a6-4280-96f3-7b9a4352e88c"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17dc6a29-ec87-4ced-a7a5-02e3470f79b7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89b7832c-a869-435b-ba28-341c86f8434b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Click = m_PlayerInput.FindAction("Click", throwIfNotFound: true);
        m_PlayerInput_LeftHold = m_PlayerInput.FindAction("LeftHold", throwIfNotFound: true);
        m_PlayerInput_RClick = m_PlayerInput.FindAction("RClick", throwIfNotFound: true);
        m_PlayerInput_Scroll = m_PlayerInput.FindAction("Scroll", throwIfNotFound: true);
        m_PlayerInput_MouseDelta = m_PlayerInput.FindAction("MouseDelta", throwIfNotFound: true);
        m_PlayerInput_MousePos = m_PlayerInput.FindAction("MousePos", throwIfNotFound: true);
        m_PlayerInput_PrimaryFingerPosition = m_PlayerInput.FindAction("PrimaryFingerPosition", throwIfNotFound: true);
        m_PlayerInput_SecondaryFingerPosition = m_PlayerInput.FindAction("SecondaryFingerPosition", throwIfNotFound: true);
        m_PlayerInput_PrimaryFingerDelta = m_PlayerInput.FindAction("PrimaryFingerDelta", throwIfNotFound: true);
        m_PlayerInput_TouchHold = m_PlayerInput.FindAction("TouchHold", throwIfNotFound: true);
        m_PlayerInput_TouchPress = m_PlayerInput.FindAction("TouchPress", throwIfNotFound: true);
        m_PlayerInput_SecondaryTouchContact = m_PlayerInput.FindAction("SecondaryTouchContact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private IPlayerInputActions m_PlayerInputActionsCallbackInterface;
    private readonly InputAction m_PlayerInput_Click;
    private readonly InputAction m_PlayerInput_LeftHold;
    private readonly InputAction m_PlayerInput_RClick;
    private readonly InputAction m_PlayerInput_Scroll;
    private readonly InputAction m_PlayerInput_MouseDelta;
    private readonly InputAction m_PlayerInput_MousePos;
    private readonly InputAction m_PlayerInput_PrimaryFingerPosition;
    private readonly InputAction m_PlayerInput_SecondaryFingerPosition;
    private readonly InputAction m_PlayerInput_PrimaryFingerDelta;
    private readonly InputAction m_PlayerInput_TouchHold;
    private readonly InputAction m_PlayerInput_TouchPress;
    private readonly InputAction m_PlayerInput_SecondaryTouchContact;
    public struct PlayerInputActions
    {
        private @HCInputAction m_Wrapper;
        public PlayerInputActions(@HCInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_PlayerInput_Click;
        public InputAction @LeftHold => m_Wrapper.m_PlayerInput_LeftHold;
        public InputAction @RClick => m_Wrapper.m_PlayerInput_RClick;
        public InputAction @Scroll => m_Wrapper.m_PlayerInput_Scroll;
        public InputAction @MouseDelta => m_Wrapper.m_PlayerInput_MouseDelta;
        public InputAction @MousePos => m_Wrapper.m_PlayerInput_MousePos;
        public InputAction @PrimaryFingerPosition => m_Wrapper.m_PlayerInput_PrimaryFingerPosition;
        public InputAction @SecondaryFingerPosition => m_Wrapper.m_PlayerInput_SecondaryFingerPosition;
        public InputAction @PrimaryFingerDelta => m_Wrapper.m_PlayerInput_PrimaryFingerDelta;
        public InputAction @TouchHold => m_Wrapper.m_PlayerInput_TouchHold;
        public InputAction @TouchPress => m_Wrapper.m_PlayerInput_TouchPress;
        public InputAction @SecondaryTouchContact => m_Wrapper.m_PlayerInput_SecondaryTouchContact;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterface != null)
            {
                @Click.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnClick;
                @LeftHold.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnLeftHold;
                @LeftHold.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnLeftHold;
                @LeftHold.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnLeftHold;
                @RClick.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnRClick;
                @RClick.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnRClick;
                @RClick.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnRClick;
                @Scroll.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnScroll;
                @Scroll.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnScroll;
                @Scroll.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnScroll;
                @MouseDelta.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMouseDelta;
                @MousePos.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMousePos;
                @MousePos.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMousePos;
                @MousePos.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMousePos;
                @PrimaryFingerPosition.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPrimaryFingerPosition;
                @PrimaryFingerPosition.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPrimaryFingerPosition;
                @PrimaryFingerPosition.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPrimaryFingerPosition;
                @SecondaryFingerPosition.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSecondaryFingerPosition;
                @SecondaryFingerPosition.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSecondaryFingerPosition;
                @SecondaryFingerPosition.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSecondaryFingerPosition;
                @PrimaryFingerDelta.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPrimaryFingerDelta;
                @PrimaryFingerDelta.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPrimaryFingerDelta;
                @PrimaryFingerDelta.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPrimaryFingerDelta;
                @TouchHold.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTouchHold;
                @TouchHold.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTouchHold;
                @TouchHold.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTouchHold;
                @TouchPress.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTouchPress;
                @TouchPress.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTouchPress;
                @TouchPress.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTouchPress;
                @SecondaryTouchContact.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSecondaryTouchContact;
                @SecondaryTouchContact.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSecondaryTouchContact;
                @SecondaryTouchContact.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSecondaryTouchContact;
            }
            m_Wrapper.m_PlayerInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @LeftHold.started += instance.OnLeftHold;
                @LeftHold.performed += instance.OnLeftHold;
                @LeftHold.canceled += instance.OnLeftHold;
                @RClick.started += instance.OnRClick;
                @RClick.performed += instance.OnRClick;
                @RClick.canceled += instance.OnRClick;
                @Scroll.started += instance.OnScroll;
                @Scroll.performed += instance.OnScroll;
                @Scroll.canceled += instance.OnScroll;
                @MouseDelta.started += instance.OnMouseDelta;
                @MouseDelta.performed += instance.OnMouseDelta;
                @MouseDelta.canceled += instance.OnMouseDelta;
                @MousePos.started += instance.OnMousePos;
                @MousePos.performed += instance.OnMousePos;
                @MousePos.canceled += instance.OnMousePos;
                @PrimaryFingerPosition.started += instance.OnPrimaryFingerPosition;
                @PrimaryFingerPosition.performed += instance.OnPrimaryFingerPosition;
                @PrimaryFingerPosition.canceled += instance.OnPrimaryFingerPosition;
                @SecondaryFingerPosition.started += instance.OnSecondaryFingerPosition;
                @SecondaryFingerPosition.performed += instance.OnSecondaryFingerPosition;
                @SecondaryFingerPosition.canceled += instance.OnSecondaryFingerPosition;
                @PrimaryFingerDelta.started += instance.OnPrimaryFingerDelta;
                @PrimaryFingerDelta.performed += instance.OnPrimaryFingerDelta;
                @PrimaryFingerDelta.canceled += instance.OnPrimaryFingerDelta;
                @TouchHold.started += instance.OnTouchHold;
                @TouchHold.performed += instance.OnTouchHold;
                @TouchHold.canceled += instance.OnTouchHold;
                @TouchPress.started += instance.OnTouchPress;
                @TouchPress.performed += instance.OnTouchPress;
                @TouchPress.canceled += instance.OnTouchPress;
                @SecondaryTouchContact.started += instance.OnSecondaryTouchContact;
                @SecondaryTouchContact.performed += instance.OnSecondaryTouchContact;
                @SecondaryTouchContact.canceled += instance.OnSecondaryTouchContact;
            }
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);
    public interface IPlayerInputActions
    {
        void OnClick(InputAction.CallbackContext context);
        void OnLeftHold(InputAction.CallbackContext context);
        void OnRClick(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
        void OnPrimaryFingerPosition(InputAction.CallbackContext context);
        void OnSecondaryFingerPosition(InputAction.CallbackContext context);
        void OnPrimaryFingerDelta(InputAction.CallbackContext context);
        void OnTouchHold(InputAction.CallbackContext context);
        void OnTouchPress(InputAction.CallbackContext context);
        void OnSecondaryTouchContact(InputAction.CallbackContext context);
    }
}
