// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Games/BubblesShot/BubbleShooterEndGame.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Games/BubblesShot/BubbleShooterEndGame.proto</summary>
public static partial class BubbleShooterEndGameReflection {

  #region Descriptor
  /// <summary>File descriptor for Games/BubblesShot/BubbleShooterEndGame.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BubbleShooterEndGameReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CixHYW1lcy9CdWJibGVzU2hvdC9CdWJibGVTaG9vdGVyRW5kR2FtZS5wcm90",
          "byJ3ChRCdWJibGVTaG9vdGVyRW5kR2FtZRINCgVzY29yZRgBIAEoBRISCgpj",
          "bGVhckJvYXJkGAIgASgFEhEKCXRpbWVCb251cxgDIAEoBRITCgtmaW5hbFNj",
          "b3JlcxgEIAEoBRIUCgxnYW1lT3ZlclR5cGUYBSABKAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BubbleShooterEndGame), global::BubbleShooterEndGame.Parser, new[]{ "Score", "ClearBoard", "TimeBonus", "FinalScores", "GameOverType" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class BubbleShooterEndGame : pb::IMessage<BubbleShooterEndGame>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BubbleShooterEndGame> _parser = new pb::MessageParser<BubbleShooterEndGame>(() => new BubbleShooterEndGame());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BubbleShooterEndGame> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BubbleShooterEndGameReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BubbleShooterEndGame() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BubbleShooterEndGame(BubbleShooterEndGame other) : this() {
    score_ = other.score_;
    clearBoard_ = other.clearBoard_;
    timeBonus_ = other.timeBonus_;
    finalScores_ = other.finalScores_;
    gameOverType_ = other.gameOverType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BubbleShooterEndGame Clone() {
    return new BubbleShooterEndGame(this);
  }

  /// <summary>Field number for the "score" field.</summary>
  public const int ScoreFieldNumber = 1;
  private int score_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Score {
    get { return score_; }
    set {
      score_ = value;
    }
  }

  /// <summary>Field number for the "clearBoard" field.</summary>
  public const int ClearBoardFieldNumber = 2;
  private int clearBoard_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ClearBoard {
    get { return clearBoard_; }
    set {
      clearBoard_ = value;
    }
  }

  /// <summary>Field number for the "timeBonus" field.</summary>
  public const int TimeBonusFieldNumber = 3;
  private int timeBonus_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TimeBonus {
    get { return timeBonus_; }
    set {
      timeBonus_ = value;
    }
  }

  /// <summary>Field number for the "finalScores" field.</summary>
  public const int FinalScoresFieldNumber = 4;
  private int finalScores_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int FinalScores {
    get { return finalScores_; }
    set {
      finalScores_ = value;
    }
  }

  /// <summary>Field number for the "gameOverType" field.</summary>
  public const int GameOverTypeFieldNumber = 5;
  private int gameOverType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GameOverType {
    get { return gameOverType_; }
    set {
      gameOverType_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BubbleShooterEndGame);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BubbleShooterEndGame other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Score != other.Score) return false;
    if (ClearBoard != other.ClearBoard) return false;
    if (TimeBonus != other.TimeBonus) return false;
    if (FinalScores != other.FinalScores) return false;
    if (GameOverType != other.GameOverType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Score != 0) hash ^= Score.GetHashCode();
    if (ClearBoard != 0) hash ^= ClearBoard.GetHashCode();
    if (TimeBonus != 0) hash ^= TimeBonus.GetHashCode();
    if (FinalScores != 0) hash ^= FinalScores.GetHashCode();
    if (GameOverType != 0) hash ^= GameOverType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Score != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Score);
    }
    if (ClearBoard != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ClearBoard);
    }
    if (TimeBonus != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TimeBonus);
    }
    if (FinalScores != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(FinalScores);
    }
    if (GameOverType != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(GameOverType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Score != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Score);
    }
    if (ClearBoard != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ClearBoard);
    }
    if (TimeBonus != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TimeBonus);
    }
    if (FinalScores != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(FinalScores);
    }
    if (GameOverType != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(GameOverType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Score != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Score);
    }
    if (ClearBoard != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClearBoard);
    }
    if (TimeBonus != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TimeBonus);
    }
    if (FinalScores != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(FinalScores);
    }
    if (GameOverType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameOverType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BubbleShooterEndGame other) {
    if (other == null) {
      return;
    }
    if (other.Score != 0) {
      Score = other.Score;
    }
    if (other.ClearBoard != 0) {
      ClearBoard = other.ClearBoard;
    }
    if (other.TimeBonus != 0) {
      TimeBonus = other.TimeBonus;
    }
    if (other.FinalScores != 0) {
      FinalScores = other.FinalScores;
    }
    if (other.GameOverType != 0) {
      GameOverType = other.GameOverType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Score = input.ReadInt32();
          break;
        }
        case 16: {
          ClearBoard = input.ReadInt32();
          break;
        }
        case 24: {
          TimeBonus = input.ReadInt32();
          break;
        }
        case 32: {
          FinalScores = input.ReadInt32();
          break;
        }
        case 40: {
          GameOverType = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Score = input.ReadInt32();
          break;
        }
        case 16: {
          ClearBoard = input.ReadInt32();
          break;
        }
        case 24: {
          TimeBonus = input.ReadInt32();
          break;
        }
        case 32: {
          FinalScores = input.ReadInt32();
          break;
        }
        case 40: {
          GameOverType = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
