// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EndRoomWebsocketProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from EndRoomWebsocketProto.proto</summary>
public static partial class EndRoomWebsocketProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for EndRoomWebsocketProto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EndRoomWebsocketProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtFbmRSb29tV2Vic29ja2V0UHJvdG8ucHJvdG8iuQIKFUVuZFJvb21XZWJz",
          "b2NrZXRQcm90bxIXCg9maXJzdFVzZXJDb2RlSWQYASABKAkSFwoPYXZhdGFy",
          "Rmlyc3RVc2VyGAIgASgJEhgKEHNlY29uZFVzZXJDb2RlSWQYAyABKAkSGAoQ",
          "YXZhdGFyU2Vjb25kVXNlchgEIAEoCRIOCgZyb29tSWQYBSABKAkSEwoLZ3Jv",
          "dXBSb29tSWQYBiABKAkSEAoIbW9kZVR5cGUYByABKAUSGQoRdXNlck5hbWVG",
          "aXJzdFVzZXIYCCABKAkSGgoSdXNlck5hbWVTZWNvbmRVc2VyGAkgASgJEg4K",
          "BnJlc3VsdBgKIAEoBRIWCg5wb2ludEZpcnN0VXNlchgLIAEoBRIXCg9wb2lu",
          "dFNlY29uZFVzZXIYDCABKAUSCwoDZXhwGA0gASgDIlEKGUxpc3RFbmRSb29t",
          "V2Vic29ja2V0UHJvdG8SNAoUbGlzdEVuZFJvb21XZWJzb2NrZXQYASADKAsy",
          "Fi5FbmRSb29tV2Vic29ja2V0UHJvdG9iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::EndRoomWebsocketProto), global::EndRoomWebsocketProto.Parser, new[]{ "FirstUserCodeId", "AvatarFirstUser", "SecondUserCodeId", "AvatarSecondUser", "RoomId", "GroupRoomId", "ModeType", "UserNameFirstUser", "UserNameSecondUser", "Result", "PointFirstUser", "PointSecondUser", "Exp" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ListEndRoomWebsocketProto), global::ListEndRoomWebsocketProto.Parser, new[]{ "ListEndRoomWebsocket" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class EndRoomWebsocketProto : pb::IMessage<EndRoomWebsocketProto>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EndRoomWebsocketProto> _parser = new pb::MessageParser<EndRoomWebsocketProto>(() => new EndRoomWebsocketProto());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EndRoomWebsocketProto> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EndRoomWebsocketProtoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EndRoomWebsocketProto() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EndRoomWebsocketProto(EndRoomWebsocketProto other) : this() {
    firstUserCodeId_ = other.firstUserCodeId_;
    avatarFirstUser_ = other.avatarFirstUser_;
    secondUserCodeId_ = other.secondUserCodeId_;
    avatarSecondUser_ = other.avatarSecondUser_;
    roomId_ = other.roomId_;
    groupRoomId_ = other.groupRoomId_;
    modeType_ = other.modeType_;
    userNameFirstUser_ = other.userNameFirstUser_;
    userNameSecondUser_ = other.userNameSecondUser_;
    result_ = other.result_;
    pointFirstUser_ = other.pointFirstUser_;
    pointSecondUser_ = other.pointSecondUser_;
    exp_ = other.exp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EndRoomWebsocketProto Clone() {
    return new EndRoomWebsocketProto(this);
  }

  /// <summary>Field number for the "firstUserCodeId" field.</summary>
  public const int FirstUserCodeIdFieldNumber = 1;
  private string firstUserCodeId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FirstUserCodeId {
    get { return firstUserCodeId_; }
    set {
      firstUserCodeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "avatarFirstUser" field.</summary>
  public const int AvatarFirstUserFieldNumber = 2;
  private string avatarFirstUser_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AvatarFirstUser {
    get { return avatarFirstUser_; }
    set {
      avatarFirstUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "secondUserCodeId" field.</summary>
  public const int SecondUserCodeIdFieldNumber = 3;
  private string secondUserCodeId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SecondUserCodeId {
    get { return secondUserCodeId_; }
    set {
      secondUserCodeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "avatarSecondUser" field.</summary>
  public const int AvatarSecondUserFieldNumber = 4;
  private string avatarSecondUser_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AvatarSecondUser {
    get { return avatarSecondUser_; }
    set {
      avatarSecondUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "roomId" field.</summary>
  public const int RoomIdFieldNumber = 5;
  private string roomId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RoomId {
    get { return roomId_; }
    set {
      roomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "groupRoomId" field.</summary>
  public const int GroupRoomIdFieldNumber = 6;
  private string groupRoomId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GroupRoomId {
    get { return groupRoomId_; }
    set {
      groupRoomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "modeType" field.</summary>
  public const int ModeTypeFieldNumber = 7;
  private int modeType_;
  /// <summary>
  /// 1 -  head_to_head, 2 - knock_out, 3 -  round_robin, 4 - one_to_many
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ModeType {
    get { return modeType_; }
    set {
      modeType_ = value;
    }
  }

  /// <summary>Field number for the "userNameFirstUser" field.</summary>
  public const int UserNameFirstUserFieldNumber = 8;
  private string userNameFirstUser_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserNameFirstUser {
    get { return userNameFirstUser_; }
    set {
      userNameFirstUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "userNameSecondUser" field.</summary>
  public const int UserNameSecondUserFieldNumber = 9;
  private string userNameSecondUser_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserNameSecondUser {
    get { return userNameSecondUser_; }
    set {
      userNameSecondUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 10;
  private int result_;
  /// <summary>
  /// 1 - first user win, 2 - second user win
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "pointFirstUser" field.</summary>
  public const int PointFirstUserFieldNumber = 11;
  private int pointFirstUser_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PointFirstUser {
    get { return pointFirstUser_; }
    set {
      pointFirstUser_ = value;
    }
  }

  /// <summary>Field number for the "pointSecondUser" field.</summary>
  public const int PointSecondUserFieldNumber = 12;
  private int pointSecondUser_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PointSecondUser {
    get { return pointSecondUser_; }
    set {
      pointSecondUser_ = value;
    }
  }

  /// <summary>Field number for the "exp" field.</summary>
  public const int ExpFieldNumber = 13;
  private long exp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Exp {
    get { return exp_; }
    set {
      exp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EndRoomWebsocketProto);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EndRoomWebsocketProto other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (FirstUserCodeId != other.FirstUserCodeId) return false;
    if (AvatarFirstUser != other.AvatarFirstUser) return false;
    if (SecondUserCodeId != other.SecondUserCodeId) return false;
    if (AvatarSecondUser != other.AvatarSecondUser) return false;
    if (RoomId != other.RoomId) return false;
    if (GroupRoomId != other.GroupRoomId) return false;
    if (ModeType != other.ModeType) return false;
    if (UserNameFirstUser != other.UserNameFirstUser) return false;
    if (UserNameSecondUser != other.UserNameSecondUser) return false;
    if (Result != other.Result) return false;
    if (PointFirstUser != other.PointFirstUser) return false;
    if (PointSecondUser != other.PointSecondUser) return false;
    if (Exp != other.Exp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (FirstUserCodeId.Length != 0) hash ^= FirstUserCodeId.GetHashCode();
    if (AvatarFirstUser.Length != 0) hash ^= AvatarFirstUser.GetHashCode();
    if (SecondUserCodeId.Length != 0) hash ^= SecondUserCodeId.GetHashCode();
    if (AvatarSecondUser.Length != 0) hash ^= AvatarSecondUser.GetHashCode();
    if (RoomId.Length != 0) hash ^= RoomId.GetHashCode();
    if (GroupRoomId.Length != 0) hash ^= GroupRoomId.GetHashCode();
    if (ModeType != 0) hash ^= ModeType.GetHashCode();
    if (UserNameFirstUser.Length != 0) hash ^= UserNameFirstUser.GetHashCode();
    if (UserNameSecondUser.Length != 0) hash ^= UserNameSecondUser.GetHashCode();
    if (Result != 0) hash ^= Result.GetHashCode();
    if (PointFirstUser != 0) hash ^= PointFirstUser.GetHashCode();
    if (PointSecondUser != 0) hash ^= PointSecondUser.GetHashCode();
    if (Exp != 0L) hash ^= Exp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (FirstUserCodeId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(FirstUserCodeId);
    }
    if (AvatarFirstUser.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AvatarFirstUser);
    }
    if (SecondUserCodeId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(SecondUserCodeId);
    }
    if (AvatarSecondUser.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(AvatarSecondUser);
    }
    if (RoomId.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(RoomId);
    }
    if (GroupRoomId.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(GroupRoomId);
    }
    if (ModeType != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(ModeType);
    }
    if (UserNameFirstUser.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(UserNameFirstUser);
    }
    if (UserNameSecondUser.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(UserNameSecondUser);
    }
    if (Result != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(Result);
    }
    if (PointFirstUser != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(PointFirstUser);
    }
    if (PointSecondUser != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(PointSecondUser);
    }
    if (Exp != 0L) {
      output.WriteRawTag(104);
      output.WriteInt64(Exp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (FirstUserCodeId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(FirstUserCodeId);
    }
    if (AvatarFirstUser.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AvatarFirstUser);
    }
    if (SecondUserCodeId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(SecondUserCodeId);
    }
    if (AvatarSecondUser.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(AvatarSecondUser);
    }
    if (RoomId.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(RoomId);
    }
    if (GroupRoomId.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(GroupRoomId);
    }
    if (ModeType != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(ModeType);
    }
    if (UserNameFirstUser.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(UserNameFirstUser);
    }
    if (UserNameSecondUser.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(UserNameSecondUser);
    }
    if (Result != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(Result);
    }
    if (PointFirstUser != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(PointFirstUser);
    }
    if (PointSecondUser != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(PointSecondUser);
    }
    if (Exp != 0L) {
      output.WriteRawTag(104);
      output.WriteInt64(Exp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (FirstUserCodeId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstUserCodeId);
    }
    if (AvatarFirstUser.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarFirstUser);
    }
    if (SecondUserCodeId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SecondUserCodeId);
    }
    if (AvatarSecondUser.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarSecondUser);
    }
    if (RoomId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomId);
    }
    if (GroupRoomId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupRoomId);
    }
    if (ModeType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ModeType);
    }
    if (UserNameFirstUser.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserNameFirstUser);
    }
    if (UserNameSecondUser.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserNameSecondUser);
    }
    if (Result != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
    }
    if (PointFirstUser != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PointFirstUser);
    }
    if (PointSecondUser != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PointSecondUser);
    }
    if (Exp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Exp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EndRoomWebsocketProto other) {
    if (other == null) {
      return;
    }
    if (other.FirstUserCodeId.Length != 0) {
      FirstUserCodeId = other.FirstUserCodeId;
    }
    if (other.AvatarFirstUser.Length != 0) {
      AvatarFirstUser = other.AvatarFirstUser;
    }
    if (other.SecondUserCodeId.Length != 0) {
      SecondUserCodeId = other.SecondUserCodeId;
    }
    if (other.AvatarSecondUser.Length != 0) {
      AvatarSecondUser = other.AvatarSecondUser;
    }
    if (other.RoomId.Length != 0) {
      RoomId = other.RoomId;
    }
    if (other.GroupRoomId.Length != 0) {
      GroupRoomId = other.GroupRoomId;
    }
    if (other.ModeType != 0) {
      ModeType = other.ModeType;
    }
    if (other.UserNameFirstUser.Length != 0) {
      UserNameFirstUser = other.UserNameFirstUser;
    }
    if (other.UserNameSecondUser.Length != 0) {
      UserNameSecondUser = other.UserNameSecondUser;
    }
    if (other.Result != 0) {
      Result = other.Result;
    }
    if (other.PointFirstUser != 0) {
      PointFirstUser = other.PointFirstUser;
    }
    if (other.PointSecondUser != 0) {
      PointSecondUser = other.PointSecondUser;
    }
    if (other.Exp != 0L) {
      Exp = other.Exp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          FirstUserCodeId = input.ReadString();
          break;
        }
        case 18: {
          AvatarFirstUser = input.ReadString();
          break;
        }
        case 26: {
          SecondUserCodeId = input.ReadString();
          break;
        }
        case 34: {
          AvatarSecondUser = input.ReadString();
          break;
        }
        case 42: {
          RoomId = input.ReadString();
          break;
        }
        case 50: {
          GroupRoomId = input.ReadString();
          break;
        }
        case 56: {
          ModeType = input.ReadInt32();
          break;
        }
        case 66: {
          UserNameFirstUser = input.ReadString();
          break;
        }
        case 74: {
          UserNameSecondUser = input.ReadString();
          break;
        }
        case 80: {
          Result = input.ReadInt32();
          break;
        }
        case 88: {
          PointFirstUser = input.ReadInt32();
          break;
        }
        case 96: {
          PointSecondUser = input.ReadInt32();
          break;
        }
        case 104: {
          Exp = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          FirstUserCodeId = input.ReadString();
          break;
        }
        case 18: {
          AvatarFirstUser = input.ReadString();
          break;
        }
        case 26: {
          SecondUserCodeId = input.ReadString();
          break;
        }
        case 34: {
          AvatarSecondUser = input.ReadString();
          break;
        }
        case 42: {
          RoomId = input.ReadString();
          break;
        }
        case 50: {
          GroupRoomId = input.ReadString();
          break;
        }
        case 56: {
          ModeType = input.ReadInt32();
          break;
        }
        case 66: {
          UserNameFirstUser = input.ReadString();
          break;
        }
        case 74: {
          UserNameSecondUser = input.ReadString();
          break;
        }
        case 80: {
          Result = input.ReadInt32();
          break;
        }
        case 88: {
          PointFirstUser = input.ReadInt32();
          break;
        }
        case 96: {
          PointSecondUser = input.ReadInt32();
          break;
        }
        case 104: {
          Exp = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ListEndRoomWebsocketProto : pb::IMessage<ListEndRoomWebsocketProto>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ListEndRoomWebsocketProto> _parser = new pb::MessageParser<ListEndRoomWebsocketProto>(() => new ListEndRoomWebsocketProto());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ListEndRoomWebsocketProto> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EndRoomWebsocketProtoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ListEndRoomWebsocketProto() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ListEndRoomWebsocketProto(ListEndRoomWebsocketProto other) : this() {
    listEndRoomWebsocket_ = other.listEndRoomWebsocket_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ListEndRoomWebsocketProto Clone() {
    return new ListEndRoomWebsocketProto(this);
  }

  /// <summary>Field number for the "listEndRoomWebsocket" field.</summary>
  public const int ListEndRoomWebsocketFieldNumber = 1;
  private static readonly pb::FieldCodec<global::EndRoomWebsocketProto> _repeated_listEndRoomWebsocket_codec
      = pb::FieldCodec.ForMessage(10, global::EndRoomWebsocketProto.Parser);
  private readonly pbc::RepeatedField<global::EndRoomWebsocketProto> listEndRoomWebsocket_ = new pbc::RepeatedField<global::EndRoomWebsocketProto>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EndRoomWebsocketProto> ListEndRoomWebsocket {
    get { return listEndRoomWebsocket_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ListEndRoomWebsocketProto);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ListEndRoomWebsocketProto other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!listEndRoomWebsocket_.Equals(other.listEndRoomWebsocket_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= listEndRoomWebsocket_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    listEndRoomWebsocket_.WriteTo(output, _repeated_listEndRoomWebsocket_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    listEndRoomWebsocket_.WriteTo(ref output, _repeated_listEndRoomWebsocket_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += listEndRoomWebsocket_.CalculateSize(_repeated_listEndRoomWebsocket_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ListEndRoomWebsocketProto other) {
    if (other == null) {
      return;
    }
    listEndRoomWebsocket_.Add(other.listEndRoomWebsocket_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          listEndRoomWebsocket_.AddEntriesFrom(input, _repeated_listEndRoomWebsocket_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          listEndRoomWebsocket_.AddEntriesFrom(ref input, _repeated_listEndRoomWebsocket_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
